FROM python:3.12-slim-bookworm@sha256:9901e0a8d75037d8242ed43155cbcb2d1f61be1356383d8054afb59fd50e39c4
COPY shell_linux_fresh_tui.py test_shell_linux_fresh_tui.py /tests/
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /tests
USER 1000:1000
CMD ["python3", "-m", "unittest", "-v", "test_shell_linux_fresh_tui"]
